apiVersion: 1

datasources:
  - name: ClickHouse
    uid: PDEE91DDB90597936
    type: grafana-clickhouse-datasource
    isDefault: true
    jsonData:
      host: clickhouse
      port: 8123
      protocol: http
      username: default
      defaultDatabase: default
    secureJsonData:
      password: ""
    editable: false

  - name: Prometheus
    uid: PBFA97CFB590B2093
    type: prometheus
    url: http://prometheus:9090
    isDefault: false
    editable: false
